import Foundation
import FwiCore

let errorDomain = "vn.vato.Client"

enum Text: String {
    // A
    case agree = "Đồng ý"
    case accountError = "Xảy ra lỗi trong quá trình đăng nhập, bạn vui lòng kiểm tra lại thông tin đăng nhập hoặc goi 19006667 để được hỗ trợ"
    case addBlacklist = "Chặn tài xế này"
    case addFavorite = "Thêm vào tài xế riêng"
    case allDriversAreBusy = "Hiện tại các xe đều đang bận. Quý khách vui lòng chọn dịch vụ khác của VATO hoặc thử lại sau ít phút."
    case amountOfMoney = "Số tiền"
    case amountToRecharge = "Số tiền muốn nạp"
    case and = "và"
    case authenticationCodeExpired = "Mã xác thực hết hạn. Gửi lại mã ngay!"
    case addFavoritePlace = "Thêm địa điểm"
    case address = "Địa chỉ"
    case addOtherService = "Thêm dịch vụ khác"
    case authorizeOpenCameraScanTicket = "Bạn cần cấp quyền mở camera để scan vé"
    case authorizeOpenPhotoGetTicket = "Bạn cần cấp quyền mở Photo để lấy hình vé"
    case afternoon = "Buổi chiều:"
    case addressEmail = "Địa chỉ email"
    case aboutDistance = "Cách %d"
    case accountIsBlocked = "Khoá tài khoản"
    case approved = "Đã duyệt"
    case addressShop = "Địa chỉ cửa hàng"
    case addNewDishes = "Thêm món mới"
    case addNewOutletContent = "Thêm cửa hàng để bắt đầu kinh doanh nhé"
    case addNewOutlet = "Thêm cửa hàng mới"
    case addMerchant = "Thêm merchant"
    case addShopToConnect = "Tìm cửa hàng để kết nối"
    case addCard = "Thêm thẻ"
    case addCardSupport1 = "Hệ thống không lưu thông tin thẻ"
    case addCardSupport2 = "Tiện dụng cho lần thanh toán sau này"
    case addFirstCardSuccess = "Tài khoản của bạn sẽ bị trừ 5.000đ cho lần đầu thêm thẻ. Số tiền này sẽ được cộng vào tài khoản VATO Pay của bạn ngay lập tức"
    case argreeWith = ", bạn đồng ý với "
    case all = "Tất cả"
    case askNextInfo = "Bạn có muốn điền thêm thông tin gói hàng không?"
    case askEmailInfo = "Bạn có muốn điền thông tin email người gửi không?"
    case messageBlockDriver = "Bạn chắc chắn muốn chặn tài xế này?"
    case messageRemoveBlockDriver = "Bạn chắc chắn muốn xoá chặn tài xế này?"

    // B
    case baseOnActualRoute = "Theo lộ trình thực tế"
    case balance = "Số dư khả dụng"
    case blacklist = "Danh sách chặn"
    case bookWithoutDestination = "Đặt xe không cần điểm đến"
    case bookingFeedback = "Phản hồi đặt xe"
    case booking = "Đặt xe"
    case blockDriver = "Chặn tài xế"
    case removeBlockDriver = "Xoá khỏi danh sách chặn"
    case blockDriverMess = "Để không gặp lại lái xe có dịch vụ kém, bạn có thể lưu lái xe vào danh sách này bằng cách chọn Thêm lái xe."
    case backToMainPage = "Quay về màn hình chính"
    case bed = "Gường"
    case buyTicketExpried = "Giao dịch của bạn đã quá 10 phút. Xin vui lòng đặt vé lại"
    case buyTicketSomeoneElse = "Bạn có muốn mua vé cho người khác không?"
    case buyTicketSuccess = "Chúc mừng bạn đã mua vé thành công"
    case badRequest = "Yêu cầu truy cập quá tải"
    case bookTicketNotSuccess = "Đặt chỗ bị lỗi"
    case byPress = "Bằng việc liên kết thẻ"
    case back = "Quay lại"
    // C
    case cannotContinueWithBookingRequest = "Hiện tại bạn chưa thể tiếp tục đặt xe, vui lòng thử lại sau.";
    case cash = "Tiền mặt"
    case check = "Kiểm tra"
    case contactDriver = "Đang liên hệ với lái xe"
    case calculateBaseOnActualMoving = "Tính theo lộ trình thực tế"
    case cancel = "Huỷ"
    case cannotPayDebt = "Không thể thanh toán khoản nợ hiện tại với phương thức thanh toán này, vui lòng chọn phương thức thanh toán khác."
    case changePincode = "Đổi mật khẩu thanh toán"
    case changePincodeDescription = "Mật khẩu thanh toán dùng để xác thực mỗi khi thực hiện chuyển và rút tiền"
    case chooseServices = "Chọn dịch vụ"
    case confirm = "Xác nhận"
    case confirmPickDestinationLocation = "Chọn điểm đến trên bản đồ"
    case confirmPickOriginLocation = "Chọn điểm đón trên bản đồ"
    case `continue` = "Tiếp tục"
    case connectWith = "Hoặc kết nối cùng"
    case copy = "Sao chép"
    case copied = "Đã sao chép"
    case currentPin = "Vị Trí Ghim"
    case cannotAccessContact = "Bạn không được quyền truy cập danh bạ. Vui lòng vào thiết lập để cấp quyền cho Vato truy cập danh bạ!"
    case callDriver = "Gọi tài xế"
    case confirmDelivery = "Xác nhận đặt hàng"
    case call = "Gọi điện"
    case cannotLoadUserInfo = "Chưa tải được thông tin khách hàng, vui lòng thử lại!"
    case congratulationsScanOffer = "Chúc mừng bạn nhận được ưu đãi từ VATO"
    case congratulationsReceivingoneyVATOPay = "Chúc mừng bạn nhận được số tiền vào VATOPay"
    case cannotFindValidQRCode = "Không tìm thấy mã QR code hợp lệ"
    case changeTicket = "Đổi vé"
    case cancelTicket = "Huỷ vé"
    case cancellationPriceTicket = "Phí huỷ"
    case cancellationTimeTicket = "Thời gian huỷ"
    case cancellationFeeContent = "Phí huỷ sẽ được tính trên giá gốc, không giảm trừ khuyến mãi hoặc giảm giá."
    case cancellationPaymentFee = "Thanh toán phí huỷ"
    case cancellationCofirm = "Xác nhận huỷ vé"
    case cancellationFeeDetail = "Chi tiết phí huỷ"
    case cancellationMoneyRefund = "Tiền nhận lại"
    case cancellationFeeTicker = "Phí huỷ vé"
    case cancellationTickerSuccess = "Huỷ vé thành công"
    case cancellationTicketSuccessContent = "Quý khách đã huỷ vé thành công."
    case cancellationTicketFailureContent = "Quý khách không thể huỷ vé này vì đã hết thời gian huỷ vé"
    case changeTicketContent = "Quý khách được quyền đổi vé một lần duy nhất trước giờ xe chạy 24h \n Quý khách vui lòng liên hệ chúng tôi qua tổng đài 19006067 để được hỗ trợ"
    case chooseDateToContinue = "Chọn ngày để tiếp tục!"
    case completeInformationToContinue = "Điền đầy đủ thông tin để tiếp tục"
    case customerInformation = "Thông tin khách hàng"
    case checkPromotionList = "Kiểm tra mục Khuyến mãi"
    case choose = "Chọn"
    case contactManagement = "Gọi tổng đài VATO"
    case checkNetworkBad = "Mạng đang chậm, vui lòng thử lại sau"
    case certificateATTP = "3. Giấy chứng nhận ATTP"
    case closeTime = "Giờ đóng cửa"
    case categories = "Danh mục"
    case certificateBusiness = "1.Giấy chứng nhận ĐKDN"
    case changeImageMerchant = "Đổi ảnh"
    case categoriesNotEmpty = "Danh mục không được để trống"
    case chooseExistPhoto = "Chụp hình trong thư viện"
    case cancellationDescription = "Vui lòng cho Vato biết lý do huỷ chuyến. Phản hồi của bạn rất quý cho chúng tôi."
    case confirmChangeTicket = "Xác nhận đổi vé"
    case changeTicketFee = "Phí đổi vé :"
    case changingTicket = "Quý khách đang đổi vé khác tuyến"
    case contentChangeTicketFee = "Hệ thống sẽ huỷ vé %@, tuyến %@, hoàn tiền %@ vào tài khoản VATOPay và tiến hành mua vé mới cho quý khách.\nPhí đổi vé : %@"
    case changePaymentMethod = "Thay đổi hình thức thanh toán"
    case contractCarOrder = "Đơn hàng xe hợp đồng"
    // D
    case depositMethod = "Kênh nạp tiền"
    case destinationBaseOnYourRequest = "Điểm đến theo yêu cầu của bạn"
    case detailPrice = "Chi tiết giá"
    case detroyPromotion = "Sử dụng sau"
    case dismiss = "Đóng"
    case driverInfo = "Thông tin tài xế"
    case driversAreReceivingYourBookingRequest = "Các tài xế đang xem yêu cầu cuốc xe của bạn"
    case driversDeliverAreReceivingYourBookingRequest = "Các tài xế đang xem yêu cầu giao hàng của bạn"
    case deletePlace = "Xóa địa chỉ"
    case deleteThisPlaceConfirm = "Bạn có muốn xóa địa chỉ này không?"
    case delivery = "Giao hàng"
    case deliverySuccess = "Giao hàng thành công"
    case deliveryFail = "Giao hàng thất bại"
    
    case deliverySender = "Thông tin người gửi"
    case deliveryInputSender = "Bấm vào đây để điền thông tin người gửi"
    case deliveryReceiver = "Thông tin người nhận"
    case deliveryInputReceiver = "Bấm vào đây để điền thông tin người nhận"
    
    case deliveryInputAdressReceiverPlaceholder = "Nhập địa chỉ người nhận"
    case deliveryInputNameReceiverPlaceholder = "Họ và tên người nhận"
    case deliveryInputPhoneReceiverPlaceholder = "Số điện thoại người nhận"
    
    case deliveryInputAdressSenderPlaceholder = "Nhập địa chỉ người gửi"
    case deliveryInputNameSenderPlaceholder = "Họ và tên người gửi"
    case deliveryInputPhoneSenderPlaceholder = "Số điện thoại người gửi"
    
    case deliveryTitleAdressSender = "Nhận hàng tại"
    case deliveryTitleAdressReceiver = "Giao hàng tới"
    case deliveryTitleAdressReceiverPlaceHolder = "Bạn muốn giao hàng đến đâu?"
    
    case deliveryRequire = "Yêu cầu gói hàng"
    case deliveryWeightRequire = " - Trọng lượng: nhỏ hơn 5kg"
    case deliverySizeRequire = " - Kích thước: 50x60x40cm"
    case deliveryReceiverIsMe = "Tôi là người nhận"
    case deliveryCancel = "Huỷ giao hàng"
    
    case distance = "Quãng đường"
    case downloadMomo = "Tải MoMo"
    case departure = "Điểm khởi hành"
    case dateDeparture = "Ngày khởi hành"
    case dateReturn = "Ngày về"
    case departureTime = "Thời gian khởi hành"
    case donotHaveTrip = "Bạn không tìm được chuyến xe"
    case donotHaveOriginLocation = "Bạn không tìm được điểm đi"
    case donotHaveDestinationLocation = "Bạn không tìm được điểm đến"
    case donotHaveDepartureTime = "Bạn không tìm được thời gian bắt đầu chuyến đi"
    case donotHavePickupLocation = "Bạn không tìm được điểm lên xe"
    case donotHaveSeats = "Bạn không tìm được ghế"
    case donotHaveTicket = "Bạn chưa có vé"
    case dataConflict = "Xung đột dữ liệu"
    case donotConnectMerchant = "Chưa kết nối dữ liệu Merchant"
    case descriptionDishes = "Mô tả"
    case detailMerchant = "Chi tiết Merchant"
    case detailDescription = "Mô tả chi tiết"
    case detailProblem = "Mô tả chi  tiết vấn đề của bạn"
    case dontSupportATMLocalYet = "Chưa hỗ trợ thẻ ATM nội địa"
    case driverCancelled = "Tài xế hủy"
    case detailRoute = "Lịch trình"
    case desDetailRoute = "Thời gian dừng chân ở mỗi nơi có thể sớm hoặc trễ hơn dự kiến ban đầu do mật độ lưu thông trên đường, mọi nhu cầu giải đáp thắc mắc của Quý khách sẽ được trả lời qua tổng đài chăm sóc khách hàng, phục vụ 24/24 của chúng tôi: "
    case discountTicketSeat = "Khuyến mãi "
    // E
    case email = "Email"
    case enablePrivateDriverMode = "Đã bật tính năng Lái xe riêng. VATO sẽ ưu tiên các tài xế trong danh sách yêu thích của bạn."
    case enterPhoneNumber = "Nhập số điện thoai di động"
    case error = "Lỗi"
    case errorRequestTimout = "Kết nối mạng không ổn định, vui lòng xem lại lịch sử và thử lại sau"
    case enterTheSearchAddress = "Nhập địa chỉ tìm kiếm"
    case estimateTime = "Thời gian dự kiến"
    case empty = "Trống"
    case editInformationTicket = "Sửa thông tin"
    case eating = "Ăn uống"
    case edit = "Sửa"
    // F
    case fare = "Cước phí"
    case findBestDriverForYou = "Đang tìm tài xế tốt nhất cho bạn ..."
    case findBestDriverDeliveryForYou = "Đang tìm lái xe giao hàng cho bạn ..."
    case fullname = "Họ và tên"
    case favoritePlace = "Địa điểm yêu thích"
    case findTrip = "Tìm chuyến xe"
    case floor1 = "Tầng dưới"
    case floor2 = "Tầng trên"
    case firstInformation = "Thông tin lượt đi"
    case forInfoContactManagerment = "Tài khoản của bạn đã bị khoá. Vui lòng liên hệ tổng đài VATO để giải quyết"
    case fontPhoto = "Ảnh mặt trước"
    case friday = "Thứ 6"
    case finalPriceTicketSeats = "Tổng tiền "
    // G
    case noteTitle = "Ghi chú cho lái xe"
    case notePakage = "Ghi chú về gói hàng"
    // H
    case home = "Nhà"
    case hour = "giờ"
    case handDelivery = "Giao hàng tận tay"
    case haveAcceptTermWhenPressContinue = "Bấm tiếp tục là bạn đã chấp nhận điều khoản mua vé"
    case hotLine = "Hỗ trợ: 1900 6067"
    case haveData = "Có dữ liệu"
    case hoursWork = "Giờ hoạt động"
    case historySearch = "Tìm kiếm gần đây"
    // I
    case ignore = "Bỏ qua"
    case inputDriverPhone = "Nhập số điện thoại lái xe"
    case inputVerificationCode = "Nhập mã được gửi đến số"
    case inputYourPromotionCode = "Nhập mã khuyến mãi của bạn"
    case invalidEmail = "Email không hợp lệ"
    case invalidFullname = "Họ và tên không hợp lệ"
    case invalidFullnameLengthMin = "Tên phải có ít nhất 2 ký tự"
    case invalidFullnameLengthMax = "Tên không được quá 30 ký tự"
    case invalidPhoneNumber = "Số điện thoại không hợp lệ"
    case invalidPhoneNumberLength = "Số điện thoại không thể nhiều hơn 10 chữ số."
    case invalidNickname = "Nickname của bạn chưa hợp lệ!"
    case invalidSocialAccount = "This phone number had been associated with another social account. Would you like to continue?"
    case invalidAuthenticationCode = "Mã xác thực không đúng"
    case invalidReferralCode = "Mã giới thiệu không hợp lệ"
    case inviteFriend = "Gửi lời mời!"
    case inputAddress = "Chọn Địa chỉ"
    case installMomo = "Bạn vui lòng cài đặt MoMo trước khi thanh toán"
    case invalidTicketCode = "Mã vé không đúng hoặc không tồn tại. Vui lòng kiểm tra lại"
    case informationTrip = "Thông tin chuyến đi"
    case inputFullname = "Nhập họ và tên"
    case inputPhoneNumber = "Nhập số điện thoại"
    case inputEmailAdress = "Nhập địa chỉ email"
    case inputPhoneNumberSecond = "Nhập số điện thoại 2"
    case informationTicket = "Thông tin chi tiết vé"
    case inputNote = "Nhập ghi chú"
    case internalServerError = "Lỗi trong hệ thống"
    case informationShop = "Thông tin quán"
    case indentifyCard = "2.CMND/Passport của Merchant"
    case inputIndentifyCard = "Nhập số CMND/Passport"
    case inputNumberATTP = "Nhập số chứng nhận ATTP"
    case inputInsurance = "Nhập số bảo hiểm"
    case inputLink = "Nhập liên kết"
    case inputNameDishes = "Nhập tên món"
    case imageDishes = "Hình ảnh món"
    case inputNameOutlet = "Nhập tên quán"
    // J
    case joinVato = "Tham gia cùng VATO"
    // K
    case pakageSizeSmall = "Kích thước nhỏ gọn"
    case pakageSizeBig = "Hàng kích thước lớn, cồng kềnh"
    case paymentAgain = "Thanh toán lại"
    case policyCancel = "Chính sách huỷ vé"
    case profileMerchant = "Hồ sơ Merchant"
    // L
    case later = "Để sau"
    case locationStart = "Vị Trí Đi"
    case locationEnd = "Vị Trí Đến"
    case logout = "Đăng xuất"
    case locationPickup = "Điểm lên xe"
    case limousine = "Limousine"
    case lookingForMerchantToConnect = "Tìm Merchant để kết nối vào tài khoản, yêu cầu kết nối sẽ được Admin Vato hỗ trợ trong vòng 48 tiếng"
    case licenseFoodRetail = "5. Giấy phép bán lẻ thực phẩm bắt buộc"
    case latMerchant = "Lat"
    case longMerchant = "Long"
    case linktoMerchant = "Liên kết"
    // M
    case maxLengthNickname = "Nickname của bạn phải từ 5 đến 40 ký tự"
    case minLengthFullname = "Tên của bạn phải từ 2 đến 5 từ"
    case minDistanceBetweenOriginAndDestination = "Khoảng cách giữa điểm đi và điểm đến phải lớn hơn 50 mét. Xin vui lòng chọn lại."
    case minute = "phút"
    case momoTransactionFail = "Giao dịch thanh toán không thành công, xin vui lòng kiểm tra và thử lại"
    case morning = "Buổi sáng:"
    case midNight = "Buổi khuya:"
    case menu = "Thực đơn"
    case maximumPhotoFoodRetail = "Ảnh giấy phép (tối đa 5 ảnh)"
    case monday = "Thứ 2"
//    case minLengthNickname = "Tên riêng phải có ít nhất năm ký tự."
    // N
    case networkDown = "Mất kết nối"
    case networkDownDescription = "Đường truyền mạng trên thiết bị đã mất kết nối. Vui lòng kiểm tra và thử lại."
    case nickname = "Nickname"
    case noBlacklistDrivers = "Bạn chưa chặn tài xế"
    case noDriversAcceptedBookingRequests = "Rất tiếc, chưa tìm được xe nào cho bạn. Hãy dùng thử tính năng Chủ động cước phí."
    case noFavoriteDrivers = "Hiện tại bạn chưa có lái xe riêng nào. Để tạo danh sách lái xe riêng, bạn chọn Thêm lái xe"
    case note = "Ghi chú"
    case noteForDriver = "Lưu ý cho lái xe"
    case notification = "Thông báo"
    case noPromotion = "Bạn chưa có khuyến mãi nào"
    case notEnoughVATOPay = "Không đủ số dư VATOPay"
    case notEnoughVATOPayDescription = "Bạn không đủ số dư trong VATOPay để thanh toán cho chuyến đi này, vui lòng nạp thêm hoặc chuyển sang thanh toán băng tiền mặt."
    case nameOfPlace = "Tên địa điểm"
    case addressOfPlace = "Địa chỉ địa điểm"
    case name = "Tên"
    case night = "Buổi tối:"
    case nameTrip = "Tuyến xe"
    case numberOfSeats = "Số lượng ghế"
    case numberOfBeds = "Số lượng gường"
    case nameShare = "Chia sẻ"
    case noteTicket = "Lưu ý"
    case notFound = "Không tìm thấy"
    case numberATTP = "Số chứng nhận ATTP"
    case numberInsurance = "Số bảo hiểm"
    case nameMerchant = "Tên merchant"
    case nameDishes = "Tên món"
    case nameOutlet = "Tên quán"
    // O
    case otherAmount = "Số tiền khác"
    case otherPlace = "Địa điểm khác"
    case ok = "Đồng ý "
    case openTime = "Giờ mở cửa"
    case openMerchant = "Mở bán"
    case onlyPayVisa = "Hỗ trợ thanh toán thẻ Visa/MasterCard/JCB Debit, ATM nội địa."
    case ofVatoPay = " của VATOPay"
    case ofVato = " của VATO"
    // P
    case paymentMethod = "Phương thức thanh toán"
    case payWithCash = "Thanh toán tiền mặt"
    case payWithVATOPay = "Thanh toán VATOPay"
    case payWithVisa = "Thanh toán thẻ"
    case pay = "Thanh toán"
    case pending = "Chờ duyệt"
    case pendingApproval = "Số dư chờ duyệt"
    case pickupAddress = "Điểm đón"
    case pickupAt = "Đón bạn ở"
    case pincode = "Pincode"
    case phoneNumber = "Số điện thoại"
    case phoneNumberSecond = "Số điện thoại 2"
    case phoneNumberIsAssociatedWithAnotherAccount = "SDT này đang được sử dụng với một tài khoản khác."
    case privacyPolicy = "Chính sách bảo mật"
    case privateDriver = "Lái xe riêng"
    case profileInfo = "Thông tin của bạn"
    case promotion = "Khuyến mãi"
    case promotionApplyCodeError = "Mã khuyến mãi không áp dụng cho "
    case promotionApplyForAllError = "Mã khuyến mãi không hợp lệ. Vui lòng kiểm tra lại"
    case promotionApplySuccess = "Đã áp dụng mã khuyến mãi. Tận hưởng chuyến đi cùng VATO nhé !"
    case promotionNotFound = "Không tìm thấy khuyến mãi hợp lệ nào dành cho bạn!"
    case promotionExceedDay = "Đã dùng hết số lượng mã khuyến mãi trong ngày"
    case passengerInformation = "Thông tin hành khách"
    case priceTicket = "Giá vé"
    case preconditionRequired = "Điều kiện tiên quyết"
    case promotionErrorCode = "Mã khuyến mãi không hợp lệ"
    case profileShop = "Hồ sơ quán"
    case photoBanner = "Ảnh banner (tối đa 5 ảnh)"
    case impossibleCancellationTicket = "Không thể huỷ"
    case pickupLocation = "Điểm di"
    case priceTicketSeats = "Thành tiền"
    // Q
    case quickBooking = "Đặt xe ngay"
    // R
    case roundTripTicket = "Đặt vé khứ hồi"
    case recentTransactions = "Hoạt động gần đây"
    case rechargeVATOPay = "Nạp tiền VATOPay"
    case releaseAt = "Đưa bạn đến"
    case removeBlacklist = "Xóa chặn tài xế"
    case removeFavorite = "Xóa khỏi lái xe riêng"
    case referral = "Thưởng giới thiệu"
    case referralCode = "Mã giới thiệu"
    case referralCodeIfNeccessary = "Mã giới thiệu (nếu có)"
    case requiredEmail = "Email không được để trống."
    case requiredFullname = "Họ và tên không được để trống."
    case requiredNickname = "Tên riêng không được để trống."
    case requiredPhoneNumber = "Bạn chưa nhập số điện thoại."
    case resendOTP = "Gửi lại mã"
    case reset = "Đặt lại"
    case retry = "Thử lại"
    case returnToBookingConfirm = "Quay lại màn hình đặt xe"
    case reason = "Lý do"
    case receipt = "Hoá đơn thanh toán"
    case roundTrip = "Khứ hồi"
    case remainingTrip = "Còn %@ chuyến xe"
    case remainingTicket = "Còn %@ vé"
    case returnInformation = "Thông tin lượt về"
    case rebookTicket = "Đặt lại vé"
    case reChooseSeat = "Chọn lại %@"
    case requestNotMatchRule = "Yêu cầu truy cập không khớp"
    case registerMerchant = "Đăng ký Merchant"
    case reject = "Từ chối"
    case restaurantInsurance = "4. Bảo hiểm nhà hàng"
    case resultSearch = "Kết quả tìm kiếm"
    case requestConnect = "Gửi yêu cầu kết nối"
    case reasonCancel = "Lý do huỷ chuyến"
    // S
    case slogan = "VATO - Gọi là có"
    case search = "Tìm kiếm"
    case searchPromotionNotFound = "Mã khuyến mãi của bạn không hợp lệ hoặc đã hết hạn"
    case seeMore = "Xem thêm"
    case selectPaymentMethod = "Chọn phương thức thanh toán"
    case sendingOTP = "Đang gửi mã xác thực"
    case settings = "Cài đặt"
    case support = "Tôi cần hỗ trợ"
    case savePlace = "Lưu địa chỉ"
    case sendCode = "Gửi mã"
    case scanCodeSuccessful = "Quét mã thành công"
    case seeMorePromotions = "Xem thêm khuyến mãi"
    case unsuccessful = "Không thành công"
    case selectYourDepartureTime = "Chọn thời gian của bạn"
    case selectOriginLocation = "Chọn điểm đi"
    case selectDestinationLocation = "Chọn điểm đến"
    case selectLocationPickUp = "Chọn điểm lên xe"
    case seats = "Số ghế"
    case seat = "Ghế"
    case selectSeats = "Chọn số ghế"
    case selectTrip = "Chọn Chyến xe"
    case selectedBedsCount = "Bạn đã chọn %ld gường"
    case selectSeatsCount = "Bạn đã chọn %ld ghế"
    case selectedBeds = "Đã mua"
    case selectingBeds = "Đang chọn"
    case selectBedsAgain = "Số gường của bạn đã có người chọn. Xin vui lòng chọn lại số gường"
    case selectSeatsAgain = "Số ghế của bạn đã có người chọn. Xin vui lòng chọn lại số ghế"
    case searchLocation = "Tìm kiếm địa điểm"
    case supportTicket = "Hỗ trợ"
    case selectOriginLocationTicket = "Chọn điểm khởi hành"
    case selectDestinationLocationTicket = "Chọn điểm đến "
    case selectMerchant = "Chọn Merchant"
    case serialNumberBusiness = "Số ĐKDN"
    case serialNumberIndentify = "Số CMND/Passport"
    case selectEating = "Chọn loại món"
    case saveMerchant = "Lưu"
    case selectCategories = "Chọn danh mục"
    case saturday = "Thứ 7"
    case sunday = "Chủ nhật"
    case selectTimeWork = "Chọn giờ hoạt động"
    case submitTheReason = "Gửi lý do"
    case selectSeatsChangeTicket = "Chọn ghế"
    case serviceMore = "Hỗ trợ tài xế"
    case saveInformation = "Lưu thông tin"
    case superApp = "Siêu ứng dụng di động của người Việt Nam"
    case start = "Khởi hành"
    case seatSelected = "Ghế đã chọn"
    // T
    case term = "Điều khoản dịch vụ"
    case thereWasAnError = "Đã xảy ra lỗi. Vui lòng thử lại sau!"
    case exceededTheNumberTries = "Bạn đã yêu cầu đăng nhập vượt quá số lần quy định. Vui lòng thử lại sau."
    case tipDriver = "Tip lái xe"
    case tipNow = "Tip liền tay, cả ngày may mắn"
    case total = "Tổng cộng"
    case totalPayment = "Tổng cộng thanh toán"
    case totalTopUp = "Tổng tiền nạp"
    case topUp = "Nạp tiền"
    case topUpNow = "Nạp tài khoản VATOPay"
    case topUpVATOPay = "Nạp tiền vào VATOPay để nhận nhiều ưu đãi và thanh toán nhanh chóng."
    case termAndPrivacyPolicyDescription = "Khi đăng nhập hoặc đăng ký, bạn đã đồng ý với"
    case transfers = "Chuyển tiền"
    case trip = "Chuyến đi"
    case tripCancelled = "Huỷ chuyến"
    case tripCancellationConfirm = "Xác nhận huỷ chuyến"
    case tripCancellationConfirmMessage = "Bạn thực sự muốn huỷ chuyến đi này?"
    case tripFare = "Cước phí di chuyển"
    case tripHistories = "Lịch sử đặt xe"
    case turnOnLocationFeature = "Bật dịch vụ truy cập địa điểm"
    case turnOnLocationFeatureDescription = "Việc này giúp cải thiện hoạt động đón trả khách và hỗ trợ của chúng tôi."
    case thankForUsingService = "Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi. Xin cảm ơn!"
    case totalAmount = "Tổng tiền"
    case timeTrip = "Thời gian"
    case ticketAboutToDepart = "Vé sắp khởi hành"
    case ticketUnSuccess = "Bạn thanh toán thất bại"
    case ticketUnSuccessContent = "Bạn đã mua vé không thành công do một số thông tin sai"
    case timeBeforeCancel = "Trước %@"
    case timeAfterCancel = "Sau %@"
    case totalAmountTicket = "Tổng giá tiền"
    case typeMerchant = "Loại Merchant"
    case tuesday = "Thứ 3"
    case thursday = "Thứ 5"
    case typeOfDishes = "Loại món"
    case takePhoto = "Chụp hình"
    case transhipmentPoint = "Điểm trung chuyển"
    case topupZaloSuccess = "Bạn đã nạp tiền thành công"
    case ticketDepartPrice = "Giá vé lượt đi"
    case ticketReturnPrice = "Giá vé lượt về"
    // U
    case unnamedRoad = "Unnamed Road"
    case updateFavoritePlace = "Cập nhật địa điểm"
    case unauthorized = "Không được phép truy cập"
    case updateBookTicketNotSuccess = "Cập nhật đặt chỗ không thành công"
    case updateNow = "Cập nhật ngay"
    case updateApplication = "VATO thông báo"
    case updateApplicationDescription = "Chúng tôi đã sửa lỗi và nâng cấp trải nghiệm người dùng. Thêm nhiều dịch vụ mới đáp ứng mọi nhu cầu vận chuyển, đi lại của bạn. Vui lòng cập nhật phiên bản mới nhất nhé!"
    case uploadPhoto = "Tải ảnh"
    case updateTimeWork = "Cập nhật"
    // V
    case validTo = "Có giá trị đến "
    case verifyingAuthenticationCode = "Nhập mã xác thực"
    case version = "Phiên bản"
    case vatoRec = "Lưu ý:\n- VATO khuyến khích nên mua hàng có giá niêm yết\n- Khách hàng sẽ hoàn tiền mua hộ cho Lái xe khi Lái xe đến giao hàng\n- Chỉ thanh toán chuyến qua "
    // W
    case wallet = "VATOPay"
    case warningMessagePromotion = "Mã khuyến mãi áp dụng không hợp lệ, vui lòng kiểm tra lại thông tin mã hoặc đặt xe không dùng mã khuyến mãi."
    case warningPromotion = "Đặt xe không khuyến mãi"
    case warningReviewPromotion = "Xem lại mã khuyến mãi"
    case welcomeToVato = "Chào mừng đến với VATO!"
    case welcomeToVatoDescription = "Đặt VATO Bike và VATO Car trên toàn quốc"
    case whereDoYouGo = "Bạn muốn đi đâu?"
    case withdraw = "Rút tiền"
    case workNoun = "Nơi làm việc"
    case warning = "Cảnh báo"
    case workMerchant = "Làm việc"
    case wesneday = "Thứ 4"
    // X
    // Y
    case youHaveNoActivities = "Bạn chưa có hoạt động nào"
    case yourCurrentLocation = "Bạn đang ở"
    case yourPromotion = "Khuyến mãi của bạn"
    case yourDeliveryFailed = "Chuyến giao hàng của bạn đã thất bại"
    case yourDeliverySuccess = "Chuyến giao hàng của bạn đã hoàn thành"
    // Z

    case tabbarHome = "Trang chủ"
    case tabbarHistory = "Lịch sử"
    case tabbarNotify = "Notification"
    case tabbarProfile = "Tài khoản"
    case transactions = "Giao dịch"
    case totalFirstPrice = "Tổng tiền lượt đi"
    case totalReturnPrice = "Tổng tiền lượt về"
    
    case car = "VATO Car"
    case bike = "VATO Bike"
    case location = "Địa điểm"
    case ticket = "Vé xe"
    case buyTicket = "Mua vé xe"
    case taxi = "Taxi"
    case beauty = "Làm đẹp"
    case medicine = "Mua Thuốc"
    case shop = "Shop"
    case signOutMessage = "Tài khoản của bạn đã được đăng nhập bởi một thiết bị khác."
    case manageCard = "Liên kết thẻ Visa/Master/JCB/ATM"
    case addPaymentMethod = "THÊM PHƯƠNG THỨC THANH TOÁN"
    case listCardEmpty = "Bạn chưa thêm thẻ"
    case listCard = "Danh sách thẻ"
    case homePage = "home_page_vi"
    case favoriteSaved = "Địa điểm đã lưu"
    case referralFriend = "Giới thiệu bạn bè"
    case groupVato = "Cộng đồng VATO"
    case registerVato = "Đăng ký lái xe VATO"
    case moveCamera = "Di chuyển camera đến vùng chứa mã QR để quét"
    case scanQR = "Quét mã QR"
    case inputCodeQR = "Nhập mã"
    case inputPhotoQR = "Thư viện ảnh"
    case inputCode = "Nhập mã bằng tay"

    case thisUserCreatedUsingCode = "User này đã sử dụng code"
    case thePhoneNumberDoesNotMatchTheTicketNumber = "Số điện thoại không trùng với số vé"
    case ticketCodeUsed = "Mã vé đã sử dụng"
    case wrongTicketCode = "Mã vé sai"
    case maximumNumberOfCodesReceived = "Đã nhận tối đa số mã được nhận"
    case thePromotionCodeHasRunOut = "Hết mã khuyến mãi tối đa phát"
    case promotionTimeout = "Hết thời gian khuyến mãi"
    case thereAreNoPromotions = "Không có chương trình khuyến mãi"
    case departingSoon = "Sắp khởi hành"
    case oldTicket = "Lịch sử vé"
    case timeToDepart = "Giờ xuất bến"
    case ticketCode = "Mã vé/Code"
    case ticketCodeTitle = "Mã vé/Code:"
    case endTimeTicket = "Giờ tới bến:"
    case chairTicket = "Số ghế:"
    case cancelled = "Đã huỷ"
    case success = "Thành công"
    case pendingPayment = "Chờ thanh toán"
    case listTicket = "Danh sách vé"
    
    case paymentFailed = "Thanh toán thất bại"
    case thePaymentMethodIsNotValid = "Phương thức thanh toán không hợp lệ"
    case lackOfCustomerInformation = "Thiếu thông tin khách hàng"
    case lackOfTicketInformation = "Thiếu thông tin vé"
    case ticketsHaveBeenPaidInAdvance = "Vé đã được thanh toán từ trước"
    case theTicketIsNotValidForPayment = " Vé chưa hợp lệ cho thanh toán"
    case continueBuyRoundTripTickets = "Tiếp tục mua vé khứ hồi"
    
    case messageCancelBookTicket = "Bạn có chắc chắn muốn huỷ đặt vé không?"
    case messageCancelChangeTicket = "Bạn có chắc chắn muốn huỷ quá trình đổi vé này không?"
    case haveAcceptTermWhenPressContinueFormat = "Bấm tiếp tục là bạn đã chấp nhận %@"
    case theTermsTickets = "điều khoản mua vé"
    case returnDateMustGreaterThanDepartureDate = "Ngày về phải lớn hơn ngày đi"
    case wrarningPendingTicket = "Vui lòng thanh toán trong vòng %@ để vé xe của Quý khách được hợp lệ."
    case wrarningMessagePendingTicket = "*  Nếu quý khách không thanh toán trong thời gian qui định. Hệ thống sẽ tự động khóa lệnh đặt vé của Quý khách"
    case bookingTicketSuccess = "Bạn đã đặt chỗ thành công"
    case status = "Trạng thái"
    case destination = "Điểm đến"
    case payByVATOPay = "Thanh toán bằng VATOPay"
    case payWithVATOPayMessage = "Thanh toán vé : %@. Số tiền %@ bằng VATOPay"
    case payOverLimitNapas = "Số tiền vượt quá giới hạn thanh toán qua Visa/MasterCard (%@). Vui lòng chọn hình thức thanh toán khác."
    case formatHours = "%@ giờ"
    case formatMinute = "%@ Phút"
    
    case ticketManage = "Quản lý vé"
    case newTicket = "Mua vé mới"
    case payNow = "Thanh toán ngay"
    case noData = "Không có dữ liệu"
    case thereWasAnErrorFunction = "Chức năng tạm thời gián đoạn. Vui lòng thử lại sau."
    case termOfUse = "Điều khoản sử dụng "

    case updateEmailAccount = "Cập nhật tài khoản Email"
    case updateEmailMessage = "Cập nhật Email %@ vào thông tin tài khoản của bạn để nhận các thông tin giao dịch và ưu đãi từ VATO!"
    case walletVATOPayNotEnoughBalance = "Tài khoản VATOPay không đủ số dư"
    case walletVATOPayNotEnoughBalanceMessage = "Số dư tài khoản VATOPay không đủ để thực hiện giao dịch. Vui lòng nạp thêm tiền vào tài khoản VATOPay để tiến hành thanh toán."
    case depositVATOPay = "Nạp VATOPay"
    case selectRoute = "Chọn tuyến xe"
    case royalPoints = "Điểm tín nhiệm";
    case messageHaveTrip = "Chuyến đi đã được chấp nhận. Vui lòng chờ tài xế đến"
    case noDriverFound = "Không tìm thấy lái xe"
    case storeInformation = "Thông tin cửa hàng"
    
    case whichRouteYouGo = "Bạn đi tuyến nào?"
    case whatTimeYouGo = "Bạn đi mấy giờ?"
    case whereYourPickUp = "Đón bạn ở đâu?"
    case whichChairYouChoose = "Bạn chọn ghế nào?"
    case pickADay = "Chọn ngày đi"
    case changeTicketSuccess = "Chúc mừng bạn đã đổi vé thành công"
    case seeAll = "Xem tất cả"
    
    case urbanDelivery = "GIAO NỘI THÀNH"
    case citiesDelivery = "GIAO LIÊN TỈNH"
    case fastDelivery = "Giao hàng siêu tốc"
    case done = "Xong"
    case continueChangeTicket = "Tiếp tục đổi vé"
    case youSureTocancelThisOperation = "Bạn có chắc chắn muốn huỷ thao tác này?"
    case previousSelectedBed = "Giường lượt chọn trước"
    case previousSelectedSeat = "Ghế lượt chọn trước"
    
    case addVisaMaster = "Thêm thẻ Visa/Master/JCB/ATM"
    case identityCard = "Số Chứng Minh/Căn cước/Hộ Chiếu"
    case inputIdentityCard = "Nhập số chứng minh/căn cước/hộ chiếu"
    case invalidIdentityCard = "Số Chứng Minh/Căn cước/Hộ Chiếu không hợp lệ"
    case processingTransaction = "Giao dịch đang được xử lý"
    case paymentFees = "Phí thanh toán"
    
    case productBasketNote = "Lưu ý về món"
    case addToBasket = "Thêm vào giỏ hàng"
    case yourLocation = "Vị trí của bạn"
    case map = "Bản đồ"
    case addShippingAddress = "Thêm địa chỉ giao hàng"
    
    case bikeDelivery = "Xe máy"
    case truck500Kg = "Xe tải 500kg"
    case truck1Ton = "Xe tải 1 tấn"
    case truck2Ton = "Xe tải 2 tấn"
    case packageInformation = "Thông tin gói hàng"
    case packageSize = "Kích thước"
    case packageNotes = "Ghi chú gói hàng"
    case fragileGoods = "Vd: Hàng dễ vỡ"
    case transactionDetails = "Chi tiết giao dịch"
    case transactionId = "Mã giao dịch"
    case date = "Ngày giờ"
    case unknown = "Không xác định"
    case noTripMessage = "Bạn chưa có chuyến đi nào."
    case inTrip = "Trong chuyến đi"
    case complete = "Hoàn thành"
    case clientCancel = "Khách hủy"
    case adminCancel = "Admin hủy"
    case driverMissed = "TX để trôi"
    case failure = "Thất bại"
    
    case cardDetail = "Chi tiết thẻ"
    case removeCard = "Xóa Thẻ"
    case confirmRemoveCard = "Xác nhận xoá thẻ"
    case confirmRemoveCardDetail = "Bạn có chắc muốn xoá thẻ của mình kết thúc bằng số "
    case removeCardFail = "Xoá thẻ thất bại, xin vui lòng thử lại sau"
    
    case quickSupport = "Gửi yêu cầu hỗ trợ"
    case viewRequestedLists = "Xem các yêu cầu đã gửi"
    case requestedLists = "Danh sách yêu cầu hỗ trợ"
    case sendSupport = "Gửi hỗ trợ"
    case processings = "Đang xử lý"
    case supportRequestDetails = "Chi tiết yêu cầu hỗ trợ"
    case enterMessage = "Nhập để gửi tin nhắn"
    case enterTitle = "Nhập tiêu đề"
    case title = "Tiêu đề"
    case content = "Nội dung"
    case messageEnterContentQuickSupport = "Nên nhập mã chuyến đi để VATO hỗ trợ nhanh chóng hơn"
    case messageAttackImageQuickSupport = "Ảnh đính kèm (tối đa 3 ảnh: ảnh màn hình, lịch sử chuyến đi lỗi)"
    case titleSupportRequestSuccess = "Gửi yêu cầu hỗ trợ thành công"
    case messageSupportRequestSuccess = "Yêu cầu hỗ trợ của bạn đang được xử lý và được gửi đến bộ phận tiếp nhận. Bạn sẽ nhận được thông báo khi yêu cầu được hoàn thành"
    case messageSupportRequestFail = "Gửi yêu cầu hỗ trợ không thành công. Vui lòng kiểm tra lại"
    case titleSupportRequestFail = "Gửi yêu cầu hỗ trợ không thành công"
    case messageVerifyContentQuickSupport = "Nội dung ít nhất 6 kí tự"
    case messageVerifyTitleQuickSupport = "Tiêu đề ít nhất 4 kí tự"
    case openCamera = "Mở Camera"
    case shoosePicturesFromPhoto = "Chọn hình từ Photo"
    case messagePermissionOpenCamera = "Bạn cần cấp quyền mở camera để chụp hình"
    case couldNotOpenCamera = "Không thể mở camera"
    case foodNoItem = "Chưa có cửa hàng tại khu vực của bạn."
    case greeting = "Chào %@, bạn còn ở đây không?"
    case setLocationDescription = "Bạn có thể bỏ qua bước này, hãy cho phép VATO truy cập vào vị trí của bạn."
    case accountInformation = "Thông tin tài khoản"
    case change = "Thay đổi"
    case allowAccessLocation = "Cho phép truy cập định vị"
    case useThisLocation = "Sử dụng vị trí này"
    case previousLocation = "Vị trí đã nhập trước đó"
    case feedback = "Phản hồi"
    case shortcutTitle = "Hỗ trợ nhanh"
    case shortcutInTrip = "Hỗ trợ trong chuyến đi"
    case inTripMessage = "Nhắn tin"
    case inTripArrive = "Đang đến đón: %ld Phút"
    case inTripDeliveryArrive = "Đang đến lấy hàng: %ld Phút"
    case inTripOnWay = "Đang trên đường"
    case inTripRemove = "Chuyến đi của bạn đã kết thúc. Bạn vui lòng quay lại màn hình chính để tiếp tục chuyến xe mới."
    case inTripCancel = "Chuyến đi của bạn đã bị hủy. Bạn vui lòng quay lại màn hình chính để tiếp tục chuyến xe mới."
    case inTripDeliveryRemove = "Đơn hàng của bạn đã kết thúc. Bạn vui lòng quay lại màn hình chính để tiếp tục chuyến xe mới."
    case inTripNewTrip = "Chuyến mới"
    case chatTrip = "Tin nhắn từ lái xe"
    case preorder = "Đặt lại "
    case waittingAddDestination = "Yêu cầu thêm điểm đến của bạn đang đợi Lái xe xác nhận trong <b>%d giây</b>"
    case vatoSupply = "Đi chợ"
    case keepContact = "- Giữ liên lạc với Lái xe để có thể mua hàng vừa ý nhất\n"
    case findOut = "- Quý khách có thể tìm hiểu về "
    case termOfUseService = "Điều khoản sử dụng dịch vụ"
    
    case addShoppingAddress = "Mua hàng ở đâu"
    case addShoppingAddressTitle = "Địa chỉ mua hàng"
    case notEnoughMoneyShopping = "Hiện số dư VATOPay không đủ. Bạn vui lòng nạp thêm."
    case shoppingNoteRequiredMessage = "Thông tin đơn hàng không được để trống"
    case fieldRequired = "Không được để trống"
    case orderInformation = "Thông tin đơn hàng"
    case storeLocation = "Mua hàng tại"
    case shoppingFillInformationNote = "Lưu ý:\n- Số tiền ước tính để Lái xe chuẩn bị tiền mặt mua hàng\n- Khách sẽ trả số tiền chính xác trên hoá đơn bán lẻ\n- Lái xe có quyền từ chối đơn hàng trên %@"
    case orderedItem = "Đơn đã đặt"
    case buy = "mua"
    case order = "Đặt mua"
    case basket = "Giỏ hàng"
    case deliveryTime = "Giao hàng lúc"
    case chooseDeliveryTime = "Chọn thời gian giao hàng"
    case scheduler = "Hẹn giờ"
    case asSoonAsPossible = "Giao ngay"
    case schedulePickup = "Đặt lịch lấy hàng"
    case itemPrice = "Phí đơn hàng"
    case shippingFee = "Phí giao hàng"
    case inTripDelivery = "Đang trên đường giao hàng"
    case inTripAddDestination = "Thêm điểm đến"
    case inTripAddDestinationOldPrice = "Giá cũ"
    case inTripAddDestinationNewPrice = "Giá mới"
    case inTripAddDestinationFile = "shortcut-destination-vn.json"
    case inTripCancelRequestDestination = "Huỷ yêu cầu"
    case inTripAddDestinationGuide = "Bấm vào đây để Thay đổi hoặc Thêm điểm đến nhé!"
    case choosePaymentMethod = "Chọn cách thanh toán"
    case noStoreFound = "Không tìm thấy cửa hàng"
    case confirmOrder = "Đặt hàng"
    case estimatePrice = "Số tiền ước tính"
    case orderDetail = "Đơn hàng"
    case noStoreNearby = "Chưa có cửa hàng tại khu vực của bạn rồi"
    case shoppingOriginTitle = "Nhập địa chỉ mua hàng"
    case shoppingOriginPlaceHolder = "Mua hàng tại đâu?"
    
    case shoppingNotePlaceHolder = "- 1 bó rau cần\n- 2 ký thịt bò\n- 3 ký gạo(loại 23,000đ/ký)"
    case inTripAddDestinationTimeout = "Yêu cầu thêm điểm đến của bạn đã hết thời gian quy định. Vui lòng gửi lại yêu cầu"
    case inTripAddDestinationReject = "Yêu cầu thêm điểm đến của bạn đã bị từ chối. Vui lòng gửi lại yêu cầu"
    case inTripAddDestinationRequestAgain = "Yêu cầu lại"
    case wrongFormat = "Không đúng định dạng"
    case amountExceed = "Số tiền không được vược quá "
    case emptyBasketAlert = "Giỏ hàng rỗng nên xóa giỏ hàng, vui lòng thử lại sau!"
    case paymentAlertConfirm = "VATO cam kết bảo mật. Bạn có muốn lưu lại thông tin thanh toán cho lần sử dụng sau không?"
    case no = "Không"
    
    case otherMoneySource = "Chọn thanh toán trực tiếp bằng:"
    case confirmPayment = "Xác nhận thanh toán"
    case visaMasterJCBCard = "Thẻ Visa/Master/JCB"
    case atmCard = "Thẻ ATM"
    
    case chooseBusStation = "Chọn bến xe"
    case popularRoutes = "Tuyến phổ biến"
    
    case termOfConnectCard = "Điều khoản liên kết thẻ"
    case addCardPayment = "Hỗ trợ thanh toán thẻ Visa, MasterCard, JCB"
    case addCardByGateway = "Liên kết thẻ:"
    case addCardVisa = "Liên kết thẻ Visa/ Master/ JCB"
    case addCardDomestic = "Liên kết thẻ nội địa ATM"
    case addCardAgreeTerm = "Đồng ý điều khoản"
    case addCardSupport3 = "Hệ thống VATO không lưu thông tin thẻ, chỉ lưu thông tin thanh toán để tiện dụng cho lần thanh toán sau này"
    case addCardSupport4 = "Thẻ được xác thực liên kết bằng Giao dịch 5000₫ ( được hoàn lại ngay sau khi xác thực)"
    
    
    case tapToSelect = "Bấm chọn"
    case listPickupAddress = "Danh sách điểm đón"
    case whereToPickup = "Đón bạn tại địa điểm"
    case tripHasNoAvailableSeat = "Chuyến đi khởi hành vào lúc %@ đã hết ghế. Vui lòng chọn giờ khởi hành khác"
    case ticketStartTrip = "Chiều đi"
    case ticketReturnTrip = "Chiều về"
    case guideBuyTicket = "Hướng dẫn mua vé"
    
    case singleTrip = "Một chiều"
    case kindTrip = "Hình thức"
    case customerNumber = "Số lượng khách"
    case departureDate = "Ngày đi"
    case carLevel = "Hạng xe"
    case standard = "Tiêu chuẩn"
    case seatsNumber = "Số chỗ"
    case titleContract = "Thuê xe hợp đồng"
    
    var text: String {
        return rawValue
    }

    var localizedText: String {
        return FwiLocale.localized(text)
    }
}

@objcMembers
final class LocalizeObjC: NSObject {
    static func reset() {
//        SDKConfig.initializeConfig()
        #if DEBUG
//            FwiLog.debug(FwiLocale.currentLocale)
        #endif
    }

    static func localized(for text: String) -> String {
        return FwiLocale.localized(text)
    }
}

